# Generated by Django 2.2.2 on 2019-06-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstcurdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
